### ISSUE TITLE
[travis] Error cloning dependencies git@github.com:Vauxoo/account-payment.git

### ISSUE THREAD

**Issue by osvalr** [Vauxoo/odoo-peru#50]
I'm getting the following error in #49 in travis build no. 2 and could not replicate locally using travis image.

```bash
echo "Getting addons dependencies"
Getting addons dependencies
clone_oca_dependencies ${HOME} ${TRAVIS_BUILD_DIR}/..
Warning: Permanently added the RSA host key for IP address 'xxx.xxx.xxx.xxx' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Traceback (most recent call last):
  File "/home/travis/maintainer-quality-tools/travis/clone_oca_dependencies", line 122, in <module>
    run(home, build_dir)
  File "/home/travis/maintainer-quality-tools/travis/clone_oca_dependencies", line 99, in run
    checkout_dir = git_checkout(home, depname, url, branch)
  File "/home/travis/maintainer-quality-tools/travis/clone_oca_dependencies", line 70, in git_checkout
    subprocess.check_call(command)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'clone', '-q', 'git@github.com:Vauxoo/account-payment.git', '-b', '10.0', '/home/travis/account-payment']' returned non-zero exit status 128
clone_result=$?
if [ "$clone_result" != "0"  ]; then
    echo "Error cloning dependencies"
    exit $clone_result
fi;
Error cloning dependencies
```

I see the repository `Vauxoo/account-payment` is public (forked from OCA). There is no ssh key to be set in travis settings

May am I missing something here?

**Comment by osvalr** [comment]
@moylop260 could you please give me a hand on this

**Comment by osvalr** [comment]
public projects cannot use private repo url for cloning public repositories(credits to @moylop260)
